config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: %w[index update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "orders#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :pizzas, through: :pizza_ingredients

  enum :name, {
    Onions: 0,
    Cheese: 1,
    Olives: 2
  }
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :pizzas
  has_many :promotion_codes

  enum :discount_code, {
    SAVE5: 0
  }

  scope :incomplete, -> { where(complete: false) }
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  belongs_to :order
  has_many :pizza_ingredients
  has_many :ingredients, through: :pizza_ingredients

  enum :pizza_type, {
    Margherita: 0,
    Salami: 1,
    Tonno: 2
  }

  enum :pizza_size, {
    Small: 0,
    Medium: 1,
    Large: 2
  }

  scope :filter_by_pizza_type, ->(type) { where(pizza_type: type) }
  scope :filter_by_pizza_size, ->(size) { where(pizza_size: size) }
end

app/models/pizza_ingredient.rb
class PizzaIngredient < ApplicationRecord
  belongs_to :pizza
  belongs_to :ingredient

  enum :state, {
    remove: 0,
    add: 1
  }

  scope :removed, -> { where(state: :remove) }
  scope :added, -> { where(state: :add) }
end

app/models/promotion_code.rb
class PromotionCode < ApplicationRecord
  belongs_to :order

  enum :code, {
    '2FOR1' => 0
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders or /orders.json
  def index
    @orders = Order.incomplete
                   .includes(:promotion_codes, 
                             pizzas: { pizza_ingredients: :ingredient })
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    order = Order.find(params[:id])

    if order.update(complete: true)
      redirect_to orders_url, notice: 'Order was successfully updated.'
    else
      redirect_to orders_url, notice: 'Failed to update order.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def format_date(date_obj)
    date_obj.strftime('%B %d, %Y %H:%M')
  end

  def display_added_ingredients(added_ingredients)    
    "Add: #{construct_ingredients_string(added_ingredients)}"
  end

  def display_removed_ingredients(removed_ingredients)    
    "Remove: #{construct_ingredients_string(removed_ingredients)}"
  end

  def construct_ingredients_string(pizza_ingredients)
    result = ''

    pizza_ingredients.each do |pizza_ingredient|
      result += "#{pizza_ingredient.ingredient.name}, "
    end

    result.chomp!(', ') if result.present?

    result
  end

  def print_promotion_codes(promotion_codes)
    return '-' if promotion_codes.blank?

    result = ''

    promotion_codes.each do |promotion_code|
      result += "#{promotion_code.code}, "
    end

    result.chomp!(', ') if result.present?

    result
  end

  def print_discount_code(discount_code)
    return '-' if discount_code.nil?

    discount_code
  end

  def display_total_price(order)
    price = OrderPriceCalculatorService.new(order).calculate

    number_to_currency(price, unit: '€', format: '%n%u')
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PizzaOrder
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    = yield

app/views/orders/_ingredient_list.html.haml
- if pizza_ingredients.added.any?
  %ul.circle                    
    %li                                      
      = display_added_ingredients(pizza_ingredients.added)

- if pizza_ingredients.removed.any?
  %ul.circle                    
    %li                                      
      = display_removed_ingredients(pizza_ingredients.removed)

app/views/orders/_order.html.haml
%hr
.row{:id => "#{dom_id order}"}
  .column
    %p
      = "ID: #{order.id}"
    %p
      = "Created: #{format_date(order.created_at)}"
    %p
      Promotions Codes: 
      = print_promotion_codes(order.promotion_codes)
    %p
      Discount Codes:
      = print_discount_code(order.discount_code)
    %br
    %p
      = "Total Price: #{display_total_price(order)}"

    = button_to 'Complete', order_path(order), method: :patch
  .column
    = render partial: 'pizza_list', locals: { pizza_list: order.pizzas }
  
          

app/views/orders/_pizza_list.html.haml
%p                              
  Items:                        
- pizza_list.each do |pizza|  
  %ul.square                    
    %li                                      
      = "#{pizza.pizza_type} (#{pizza.pizza_size})"

      = render partial: 'ingredient_list', locals: { pizza_ingredients: pizza.pizza_ingredients } 

app/views/orders/index.html.haml
%p{:style => "color: green"}= notice
%h1 Orders
#orders
  - @orders.each do |order|
    = render order